#include "nsISupports.idl"
#include "clICPUTime.idl"
#include "nsIVariant.idl"

[scriptable, uuid(724da207-42e3-4daf-93a8-0867eaef413c)]

interface clICPU : nsISupports
{
    clICPUTime getCurrentTime();
    nsIVariant getCurrentTimes();

    double getUsage();
    nsIVariant getUsages();

    readonly attribute PRUint32 count;
};
