#include "nsISupports.idl"

[scriptable, uuid(f85b3699-7675-4767-983d-fec8e04eee49)]

interface clICPUTime : nsISupports
{
  readonly attribute double user;
  readonly attribute double nice;
  readonly attribute double system;
  readonly attribute double idle;
  readonly attribute double io_wait;
};
