#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "clICPU.idl"

[scriptable, function, uuid(f2d40ab4-7d4a-4626-a0b6-e6c8acc6f170)]
interface clISystemMonitor : nsISupports
{
  void monitor(in nsIVariant value);
};

[scriptable, uuid(4d62df13-deee-4d5a-a7d9-2cabe54c7930)]
interface clISystem : nsISupports
{
  readonly attribute clICPU cpu;
  void registerMonitor(in wstring aTopic, in clISystemMonitor aMonitor, in long aInterval);
  void unregisterMonitor(in wstring aTopic, in clISystemMonitor aMonitor);
};
