#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "nsIDOMWindow.idl"
#include "clICPU.idl"

[scriptable, function, uuid(f2d40ab4-7d4a-4626-a0b6-e6c8acc6f170)]
interface clISystemMonitor : nsISupports
{
  void monitor(in nsIVariant value);
};

[scriptable, uuid(86937840-cba8-11df-bd3b-0800200c9a66)]
interface clISystem : nsISupports
{
  readonly attribute clICPU cpu;
  boolean addMonitor(in AString aTopic, in clISystemMonitor aMonitor, in long aInterval);
  boolean addMonitorWithOwner(in AString aTopic, in clISystemMonitor aMonitor, in long aInterval, in nsIDOMWindow aOwner);
  boolean removeMonitor(in AString aTopic, in clISystemMonitor aMonitor);
};
